sonar.organization=cesarbocel222
sonar.projectKey=CesarBocel222_Laboratorio4SO2
sonar.projectName=Laboratorio4SO2

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/vendor/**,**/coverage/**

sonar.sourceEncoding=UTF-8
