name: CI Pipeline - Laboratorio4SO2

on:
  push:
    branches: ["angie"]  
  pull_request:
    branches: ["angie"] 
jobs:
  build-and-analyze:
    name: Build, Test & SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 2. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: 3. Instalar dependencias (frontend)
        working-directory: ./frontend
        run: npm install

      - name: 4. Instalar dependencias (backend)
        working-directory: ./backend
        run: npm install

      - name: 5. Pruebas unitarias (frontend)
        working-directory: ./frontend
        run: npm test -- --watchAll=false --coverage

      - name: 6. Pruebas unitarias (backend)
        working-directory: ./backend
        run: npm test

      - name: 7. Análisis estático ESLint
        run: npx eslint . --ext .js,.jsx --max-warnings=0

      - name: 8. SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}